section:
  description: Section of Punchcard that this issue belongs to.
  color: '#c0e6ff'
  labels:
    - user management
    - content types
    - workflows
    - permissions
    - input plugins
    - revisions
    - api
    - routing
    - database
problem:
  description: 'Issues that make Punchcard feel broken or prevent us from doing further work, but otherwise work as designed. High priority.'
  color: '#ff5050'
  labels:
    - blocked
    - blocker
    - bug
    - externally blocked
    - hotfix
experience:
  description: Issues that affect a user's comprehension or overall enjoyment of Punchcard.
  color: '#ffa573'
  labels:
    - visual design
    - microcopy
    - user experience
    - developer experience
    - performance
environment:
  description: 'Environment that the issue is present in, either Punchcard core or its use as a module'
  color: '#e9e0e0'
  labels:
    - core
    - module
mindless:
  description: Issues that are necessary but less impactful for our users.
  color: '#ffd4a0'
  labels:
    - cleanup
    - legal
    - technical debt
    - experience debt
    - tests
    - greenkeeper
feedback:
  description: Issues that require further conversation to figure out how to proceed or what action steps are needed.
  color: '#db2780'
  labels:
    - request for comments
    - help wanted
    - question
    - research
    - strategy
    - stub
    - prototype
addition:
  description: Issues that will result in new functionality or releases.
  color: '#b4e051'
  labels:
    - feature
improvement:
  description: Issues that will iterate on existing functionality.
  color: '#41d6c3'
  labels:
    - enhancement
    - optimization
pending:
  description: 'Issues where action can be taken, but has not yet.'
  color: '#fdd600'
  labels:
    - under consideration
    - consumable
inactive:
  description: Issues where no actions are needed or possible. The issue is either fixed or addressed better by other issues.
  color: '#dfe9e9'
  labels:
    - invalid
    - won't fix
    - duplicate
    - on hold
epic:
  description: 'Epics track multiple stories together towards a desired outcome. Each epic should get a label unique to the core concept of the epic, usually 2-3 words. Epics should be labeled with their epic label and the `epic` label. Each story related to an epic should be labeled with that epic''s label.'
  color: '#9855d4'
  labels:
    - epic
